<div style="padding-left: 20px; padding-top: 20px;">
There is no active <img src="{$icon_interfaces}" title="network path icon" />&nbsp;<a href="{$rewriter->get_page_url('Network Paths List')}" title="List Network Paths">Network Path</a> in this configuration!<br />
<br />
If you are entering <img src="{$icon_users}" alt="mastershaper icon" />&nbsp;<a href="{$rewriter->get_page_url('Others About')}" title="About MasterShaper">MasterShaper</a> for the first time:<br />
<ul>1. Define <img src="{$icon_interfaces}" alt="interface icon" />&nbsp;<a href="{$rewriter->get_page_url('Interfaces List')}" title="List Interfaces">Interfaces</a></ul>
<ul>2. Define a <img src="{$icon_interfaces}" alt="network path icon" />&nbsp;<a href="{$rewriter->get_page_url('Network Paths List')}" title="List Network Paths">Network Path</a>&nbsp;between your <img src="{$icon_interfaces}" alt="interface icon" />&nbsp;<a href="{$rewriter->get_page_url('Interfaces List')}" title="List Interfaces">Interfaces</a></ul>
<ul>3. Define <img src="{$icon_servicelevels}" alt="service level icon" />&nbsp;<a href="{$rewriter->get_page_url('Service Levels List')}" title="List Service Levels">Service Levels</a> to guarantee, limit or priorize your traffic.</ul>
<ul>4. Create <img src="{$icon_filters}" alt="filter icon" />&nbsp;<a href="{$rewriter->get_page_url('Filters List')}" title="List Filters">Filters</a> to match on ports, protocols, DSCP bits, ...</ul>
<ul>5. Create <img src="{$icon_pipes}" alt="pipe icon" />&nbsp;<a href="{$rewriter->get_page_url('Pipes List')}" title="List Pipes">Pipes</a> and assign <img src="{$icon_filters}" alt="filter icon" />&nbsp;<a href="{$rewriter->get_page_url('Filters List')}" title="List Filters">Filters</a> to it to channelize your traffic.</ul>
<ul>6. Create <img src="{$icon_chains}" alt="chain icon" />&nbsp;<a href="{$rewriter->get_page_url('Chains List')}" title="List Chains">Chains</a>, assign <img src="{$icon_pipes}" alt="pipe icon" />&nbsp;<a href="{$rewriter->get_page_url('Pipes List')}" title="List Pipes">Pipes</a> to it and attach it to a <img src="{$icon_interfaces}" alt="network path icon" />&nbsp;<a href="{$rewriter->get_page_url('Network Paths List')}" title="List Network Paths">Network Path</a></ul>
<ul>7. Go and <img src="{$icon_rules_load}" alt="rules icon" />&nbsp;<a href="{$rewriter->get_page_url('Rules Load')}" title="Load Ruleset">load</a> your ruleset!</ul>
</div>
